### PR TITLE
💺 YPP success modal copy

### LINKED ISSUE #3493: YPP Customisation: Flow - Requirements Modal / Success/ Fail modals
## Scope

- [ ] Update copy in the success banner to 
"Your channel is now successfully enrolled to Gleev YouTube Partnership Program! You already qualified for the new sign up reward of [200 JOY] tokens. Go to Dashboard for more information." 

- [ ] Add reward for signing up to Auto-sync to config (the 200 JOY)

## Context

- https://github.com/joystream/atlas/issues/3323
Requirements modal as handled here: 
- https://github.com/Joystream/atlas/issues/3447

Screenshot 2022-12-15 at 16 48 41

Out of scope

- [ ] Custom failure banner

### PR DESCRIPTION
**Pull request by WRadoslaw**
fixes #3493

### CODE REVIEW

File: packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx [hunk 1]
```diff
@@ -402,8 +404,8 @@ export const YppAuthorizationModal: FC<YppAuthorizationModalProps> = ({
           description: (
             <>
               <DescriptionText variant="t200" as="span" color="inherit">
-                Congratulations! You just received 200 JOY as your {APP_NAME} channel is now officially enrolled in the
-                YouTube Partner Program and tied with a YouTube channel.{' '}
+                You've successfully enrolled to {APP_NAME} Youtube Partnership Programme! You already qualified for the
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx]:
```suggestion
                You've successfully enrolled to {APP_NAME} YouTube Partnership Programme! You already qualified for the
```

File: packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx [hunk 2]
```diff
@@ -402,8 +404,8 @@ export const YppAuthorizationModal: FC<YppAuthorizationModalProps> = ({
...
+                new sign up reward of {YPP_REWARD} {TOKEN} tokens.
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx]: You didn't update this: 
```
Your Youtube Videos will now be synced to your Gleev Channel, and you will partake in qualifying for other rewards of the program for content upload and referrals.
```

File: packages/atlas/src/config/configSchema.ts [hunk 3]
```diff
@@ -35,6 +35,7 @@ export const configSchema = z.object({
       googleOauthEndpoint: z.string().nullable(),
       youtubeSyncApiUrl: z.string().nullable(),
       youtubeCollaboratorMemberId: z.string().nullable(),
+      enrollmentReward: z.number(),
```
Comment (drillprop) [inline packages/atlas/src/config/configSchema.ts]: I think this should be optional. I asked Dima about this. Will let you know once confirmed

**Review by drillprop — CHANGES_REQUESTED** [review]

**Review by drillprop — CHANGES_REQUESTED** [review]
After a short discussion on discord, we decided to change this once again
if the reward price is set we should have: 
```
Your channel is now successfully enrolled to {APP_NAME} YouTube Partnership Program! You already qualified for the new sign up reward of [200 JOY] tokens. Go to Dashboard for more information.
```
If the price is not set we should have
```
Your channel is now successfully enrolled to {APP_NAME} YouTube Partnership Program! Go to Dashboard for more information.
```
We're also decided to drop the paragraph after the above i.e `All information around your activity in the program can be found in the...` We should get rid of the link here as well, the CTA button in the modal should be enough.

Sorry for the inconvenience and confusion 😓

**Review by drillprop — APPROVED** [review]
