### PR TITLE
Fix issue with not removing processing assets from MyVideos

### LINKED ISSUE #2635: Issues with processing uploads
We need to have some way to either cancel a processing upload if it's been processing for too long or offer the user an option to reupload. We could save the date at which we start processing, and if it's more than a minute or something, we remove it from processing.

To reproduce:
1. Start a big upload so it doesn't finish quickly
2. Refresh the app so you have failed upload
3. Manually modify local storage to include failed upload ID in `processingAssetsId` in uploads store

---

I have seen several reports on Discord from users that struggled with uploads processing forever, not having an option to retry when it's clear the upload failed. Some of the relevant info:

SCREENSHOT

Screenshot 2022-05-11 at 08 59 52

**Usersnap report by**: delranchorecipes@gmail.com

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2635

### CODE REVIEW

File: packages/atlas/src/providers/uploadsManager/store.ts [hunk 1]
```diff
@@ -26,11 +32,13 @@ type UploadStoreActions = {
...
   addAssetFile: (assetFile: AssetFile) => void
   setIsSyncing: (isSyncing: boolean) => void
-  removeProcessingAssetId: (contentId: string) => void
-  addProcessingAssetId: (contentId: string) => void
+  removeProcessingAsset: (contentId: string) => void
+  addProcessingAsset: (contentId: string) => void
   addNewChannelId: (channelId: string) => void
 }
 
+const THREE_MINUTES = 1000 * 60 * 3
```
Comment (kdembler) [inline packages/atlas/src/providers/uploadsManager/store.ts]: Let's call this something like `UPLOAD_PROCESSING_TIMEOUT` and move to global config. I would also change this to one minute I think

**Review by kdembler — COMMENTED** [review]
Just one comment, otherwise looks good!

**Review by kdembler — APPROVED** [review]
