### PR TITLE
Fix MyVideos filters

### LINKED ISSUE #624: Filters in My videos not working
It seems the tabs in my videos view are not properly filtering videos when it comes to "unlisted" tab, it shows all the videos, not only unlisted ones

### PR DESCRIPTION
**Pull request by drillprop**
Fix #624
Fix the problem which was brought here: https://github.com/Joystream/atlas/pull/630#issuecomment-842889836

### CODE REVIEW

**Comment by drillprop** [comment]
~~My second commit should also fix #627~~
~~I decided to not create another PR for that. They're not related but I think it will be easier to test both of them at one go.~~

**Comment by drillprop** [comment]
Just noticed, there is one more problem. Steps to reproduce 
1. Select the unlisted tab
2. Click create video
3. Create a public video


After creating a video, the video sheet should minimize and you'll see your newly created public video in the unlisted tab. An analogous situation will happen if you select the published tab and create an unlisted video.
Not sure how to tackle this, yet 

Just to clarify, tested also on `sumer`, this bug was not introduced in this PR, it was there previously.

**Review by mikkio-j — APPROVED** [review]

**Comment by mikkio-j** [comment]
> Just noticed, there is one more problem. Steps to reproduce
> 
> 1. Select the unlisted tab
> 2. Click create video
> 3. Create a public video
> 
> After creating a video, the video sheet should minimize and you'll see your newly created public video in the unlisted tab. An analogous situation will happen if you select the published tab and create an unlisted video.
> Not sure how to tackle this, yet
> 
> Just to clarify, tested also on `sumer`, this bug was not introduced in this PR, it was there previously.

Could you make new issue for that and mark it as bug? Looked into it, but not sure how to resolve it

**Comment by eldiegod** [comment]
Works good and as mentioned there is that issue, pretty sure it has to do with the fn `writeVideoDataInCache` but doesn't look easy to solve

> Just noticed, there is one more problem. Steps to reproduce
> 
>     1. Select the unlisted tab
> 
>     2. Click create video
> 
>     3. Create a public video
> 
> 
> After creating a video, the video sheet should minimize and you'll see your newly created public video in the unlisted tab. An analogous situation will happen if you select the published tab and create an unlisted video.
> Not sure how to tackle this, yet
> 
> Just to clarify, tested also on `sumer`, this bug was not introduced in this PR, it was there previously.

**Review by eldiegod — APPROVED** [review]

File: src/views/studio/MyVideosView/MyVideosView.tsx [hunk 1]
```diff
@@ -41,7 +46,7 @@ export const MyVideosView = () => {
         isPublic_eq,
       },
     },
-    { notifyOnNetworkStatusChange: true }
+    { notifyOnNetworkStatusChange: true, nextFetchPolicy: 'cache-and-network' }
```
Comment (drillprop) [inline src/views/studio/MyVideosView/MyVideosView.tsx]: This is needed because if I, for example, create a public video when I have selected the unlisted tab, it will not refetch the video if I switch to  `All videos` tab. 
Just noticed - there is a downside to this - If I create an unlisted video when I have an unlisted tab selected we will not see a thumbnail right away. 
Don't know what to do about it.

**Comment by drillprop** [comment]
Pagination is broken with these changes. I need to figure it out, what's happening

**Review by kdembler — APPROVED** [review]

**Review by kdembler — APPROVED** [review]
