### PR TITLE
Fix no empty fallback for channels

### LINKED ISSUE #1576: No empty state for Channels tab in search results
Screenshot 2021-11-09 at 17 17 15

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fix #1576

### CODE REVIEW

File: src/views/viewer/SearchView/SearchResults/SearchResults.tsx [hunk 1]
```diff
@@ -99,7 +99,9 @@ export const SearchResults: React.FC<SearchResultsProps> = React.memo(({ query }
       </SearchControls>
       <Results filtersOpen={isFiltersOpen}>
         <LimitedWidthContainer big>
-          {!loading && channels.length === 0 && videos.length === 0 && !!query ? (
+          {!loading &&
+          ((videos.length === 0 && selectedIndex === 0) || (channels.length === 0 && selectedIndex === 1)) &&
+          !!query ? (
```
Comment (drillprop) [inline src/views/viewer/SearchView/SearchResults/SearchResults.tsx]: What's is selectedIndex in this context? Is it a selected tab index?
If yes, could we change this to `selectedTabIndex`?
Also, could we store this long expression in a variable?  I think it should be more readable.

**Review by drillprop — APPROVED** [review]
