### PR TITLE
Better handling of failed uploads

### LINKED ISSUE #3130: Poor handling of failed uploads
### Problem
If you publish a video and some of its assets fail to upload, you will see this in `My uploads`:

Then, user can reconnect the file and try to upload again. However, if they don't have the file available or some other problem occured, they may see the following modal:

There are some issues with the above:

1. We don't offer an option to just close the modal and don't take any action. You are forced to either edit the video or try selecting the file again. This can be frustrating to the user. Because of the current implementation, if you click Esc, it its equal to clicking the secondary button in the dialog and results in opening the video workspace.
1. The "Edit video" option actually doesn't work - it just opens an empty video workspace and you cannot edit the video in question - implementation issue
1. I'm unsure if the "Edit video" option makes sense if we are talking about media files. Even if it worked, we currently don't allow editing the media file inside Atlas, only the thumbnail. So you still wouldn't be able to fix the issue

### Proposal
I think we need to refine this flow as uploading assets will be one of the most fundamental actions creators will take on the platform and we need to make sure that everything works smoothly. Fixing first point is probably quite easy with some basic design treatment and improving the implementation. Second point is purely technical. When it comes to the third one, I suggest we allow editing the media file if its upload has failed. Maybe it's also worth taking a more holistic look at the issue, maybe there are some other improvements we could do.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202882567635505) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #3130 

**Design**
https://www.figma.com/file/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?node-id=1133%3A11900

### CODE REVIEW

**Review by drillprop — CHANGES_REQUESTED** [review]
I didn't look at the code, but I see some issues when I was trying to re-upload a cover image file. Everything seems to be fine with a video file. Did you test this as well on images?

So when I re-uploaded the new image in my uploads view I see: 
image
As you may see, there is no title, and when I click "Try again" I'm getting an error

In addition to the above, when I go to "My videos" I see two tiles with information about broken assets: 
image
Again, one doesn't have a title and it shouldn't be here. We should have only one with the name `sdsdsa`

**Comment by kdembler** [comment]
@rafalpawlow @drillprop Since I won't be available till Monday, let's make @drillprop the primary reviewer here. However, I will want to take a look on Monday before we merge as well

File: packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx [hunk 1]
```diff
@@ -54,7 +65,9 @@ const ImageCropModalComponent: ForwardRefRenderFunction<ImageCropModalImperative
   const [editedImageHref, setEditedImageHref] = useState<string | null>(null)
   const [cropData, setCropData] = useState<ImageCropData | null>(null)
   const [editMode, setEditMode] = useState(false)
+  const [fee, setFee] = useState<FeeData>()
   const [originalBlob, setOriginalBlob] = useState<File | Blob | null>(null)
+  const { fullFee, loading } = useFee(fee?.methodName, fee?.args && showModal ? fee.args : undefined)
```
Comment (drillprop) [inline packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx:69]: I don't like the fact that we're getting fees inside ImageCropModalComponent. Can we just pass the fee to the component via props? Is it possible?  Why do we actually need this here in the first place?

File: packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.hooks.ts [hunk 2]
```diff
@@ -0,0 +1,244 @@
...
+type CreateEditChannelData = {
+  newChannel: boolean
+  metadata: ChannelInputMetadata
+  assets: ChannelAssets<ImageAsset>
+  avatarAsset: ResolvedAsset | null
+  coverAsset: ResolvedAsset | null
+  channel?: FullChannelFieldsFragment
+}
+
+type FormMethods = {
```
Comment (drillprop) [inline packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.hooks.ts]: I don't like that we need to pass these methods like this. Maybe we could pass some methods like `onUploadAvatar` or `onUploadCover`(maybe you could do something like `onUploadAssets` instead of these two) and then `onTxSync` instead? And all the react-hook-form calls do on the component level? Wdyt?

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx [hunk 3]
```diff
@@ -38,73 +48,224 @@ import {
...
 type UploadStatusProps = {
   isLast?: boolean
   asset: AssetUpload
-  size?: UploadStatusGroupSize
+  size?: 'compact' | 'large'
 }
 
+const FILE_NAME_LENGTH_LIMIT = 24
+
 export const UploadStatus: FC<UploadStatusProps> = ({ isLast = false, asset, size }) => {
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx:54]: Ok, this file is super hard to read, every function has at least 100 lines and nested ifs. I'm a little worried that this will be very bug-prone, and hard to manage. Is there any room for improvement here? Could we make some effort to clean this up a bit?

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx [hunk 4]
```diff
@@ -38,73 +48,224 @@ import {
...
+              removeAssetFromUploads(asset.id)
+            },
+          },
+          secondaryButton: {
+            text: 'Cancel',
+            onClick: () => closeConfirmationModal(),
+          },
+        })
       } else {
         startFileUpload(
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx]: What will happen if we pass just `asset` here?

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx [hunk 5]
```diff
@@ -159,17 +312,161 @@ export const UploadStatus: FC<UploadStatusProps> = ({ isLast = false, asset, siz
           id: asset.parentObject.id,
         },
         type: asset.type,
+        name: asset.name,
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx]: same here

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx [hunk 6]
```diff
@@ -159,17 +312,161 @@ export const UploadStatus: FC<UploadStatusProps> = ({ isLast = false, asset, siz
...
+          secondaryButton: {
+            text: 'Cancel',
+            onClick: () => closeConfirmationModal(),
+          },
+        })
+      } else {
+        await handleUpdate()
+      }
     } else {
       startFileUpload(
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.tsx]: same here

**Review by drillprop — CHANGES_REQUESTED** [review]
I see some layout shift, when there are two files in the upload status.  
image
Could be caused by the long name, but not sure

File: packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx (hunk 1 above)
Comment (rafalpawlow) [reply packages/atlas/src/components/_overlays/ImageCropModal/ImageCropModal.tsx:69]: It's related to this view https://www.figma.com/file/Pe1Y0nrl4mpHWs7AkuQOk5/My-uploads-page?node-id=1115%3A7968

**Comment by kdembler** [comment]
Just did a quick test of this and after selecting different video file and uploading it, my old video wasn't modified but actually a new empty video was created with the new video file. That's not desired, we should only update the existing videos from my uploads

**Comment by kdembler** [comment]
Also if my thumbnail upload fails and then I select the same file, I still get the "Different file was selected". Seems the crop isn't automatic for files that we have crop data saved for, so it produces a different image

**Comment by kdembler** [comment]
Needs rebase and change of target to `dev`

**Review by drillprop — CHANGES_REQUESTED** [review]
Unfortunately found another issue. 
1. Have two failed assets(thumbnail and video). 
image
2. Click select and select a video
3. Cancel transaction in polkadot
4. Video file disappear from upload status 
image

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts [hunk 7]
```diff
@@ -0,0 +1,280 @@
...
+        title: 'Continue with a different file?',
+        description: `This file (${
+          name.length > FILE_NAME_LENGTH_LIMIT ? shortenString(name, 16, 8) : name
+        }) is different from the one you selected before. To upload it, you’ll need to sign a blockchain transaction to confirm editing your video. Are you sure you want to continue?`,
+        type: 'warning',
+        primaryButton: {
+          text: 'Continue',
+          onClick: async () => {
+            closeConfirmationModal()
+            await cb()
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts]: Is this `async/await` redundant here?

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts [hunk 8]
```diff
@@ -0,0 +1,280 @@
...
+      openConfirmationModal({
+        fee,
+        title: 'Upload different file?',
+        description: `This file (${
+          name.length > FILE_NAME_LENGTH_LIMIT ? shortenString(name, 16, 8) : name
+        }) is different from the one you selected before. To upload it, you’ll need to sign a blockchain transaction to confirm editing your video. Are you sure you want to continue?`,
+        type: 'warning',
+        primaryButton: {
+          text: 'Upload file',
+          onClick: async () => {
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.hooks.ts]: same here?

File: packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.styles.ts [hunk 9]
```diff
@@ -123,24 +119,16 @@ type FileInfoProps = {
...
 
 export const FileInfo = styled.div<FileInfoProps>`
-  display: grid;
   align-items: center;
   width: 100%;
   max-width: 600px;
-  margin-left: ${sizes(2)};
+  margin-left: ${sizes(4)};
   color: ${cVar('colorCoreNeutral300')};
+  row-gap: ${sizes(1)};
```
Comment (drillprop) [inline packages/atlas/src/views/studio/MyUploadsView/UploadStatus/UploadStatus.styles.ts]: Does this row-gap work here? You removed `display: grid`

**Review by drillprop — CHANGES_REQUESTED** [review]

**Comment by drillprop** [comment]
Another unexpected thing happened to me: 
image
I was re-uploading the video file for `Sample-5s`, and a new file jumped to another upload group.

**Review by drillprop — APPROVED** [review]
LGTM!

**Review by kdembler — APPROVED** [review]
Seems to work like a charm. Great job @rafalpawlow!
