### PR TITLE
Fix duplicated play button on mobile

### LINKED ISSUE #1471: Duplicated play icon on iOS
IMG_2300 2

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #1471

### CODE REVIEW

File: src/shared/components/VideoPlayer/VideoPlayer.tsx [hunk 1]
```diff
@@ -499,20 +499,22 @@ const VideoPlayerComponent: React.ForwardRefRenderFunction<HTMLVideoElement, Vid
...
-                  >
-                    {playerState === 'ended' ? (
-                      <SvgPlayerRestart />
-                    ) : isPlaying ? (
-                      <SvgPlayerPause />
-                    ) : (
-                      <SvgPlayerPlay />
-                    )}
-                  </PlayButton>
+                  {!showBigPlayButton && (
```
Comment (drillprop) [inline src/shared/components/VideoPlayer/VideoPlayer.tsx]: This will remove play button on desktop view.
Zrzut ekranu 2021-11-15 o 12 47 17


@toiletgranny what do you think about it?

Comment (toiletgranny) [reply src/shared/components/VideoPlayer/VideoPlayer.tsx]: Thanks for including me in this! 

Frankly, I would recommend having the small play button visible and active in the above case scenario. This might be useful for users that have already developed a "muscle memory" for playing/pausing the video in the bottom left corner of the video player.

To have the big play button in the middle, as an addition, is ok for me, by the way.

**Review by drillprop — APPROVED** [review]
