### PR TITLE
Channel ownership of NFT

### LINKED ISSUE #3239: Show channel ownership of NFT
- [ ] Display the channel as the owner in the NftWidget
- [ ] Display the channel as the owner in the NftTile

---

**Sender**: None
**Taken at**: https://play.joystream.org/video/27410
**Fields**:
- Expected Result: On player page, the avatar used for the owner does not show the channel avatar when the NFT is owned by the channel, it shows the member. The name however correctly uses the channel name, not the member name.
- Houston, we have a problem.: Wrong ownership avatar on NFTs

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3315009d-a3e2-4f6c-baa3-67b96cb357d7-annotated_2517fe01-3a1d-4368-9d08-517c78b2f07d.png?etag=3bb41d5bf309ced77c6405bd6c4ff613)*

**Browser**: Firefox 104 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 2613x1136
**[Open #22 in Usersnap](https://app.usersnap.com/l/feedback/10a95f96-00b7-4956-8cda-9eccb0088066?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #3239

### CODE REVIEW

File: packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx [hunk 1]
```diff
@@ -193,13 +193,15 @@ export const ChannelView: FC = () => {
...
-    })) || []
+    channelNftCollectors
+      ?.filter(({ channel }) => channel?.id !== id)
+      .map(({ amount, member }) => ({
+        nftsAmount: amount,
+        url: member?.metadata.avatar?.__typename === 'AvatarUri' ? member?.metadata.avatar?.avatarUri : '',
+        tooltipText: member?.handle,
+        onClick: () => navigate(absoluteRoutes.viewer.member(member?.handle)),
+        memberUrl: absoluteRoutes.viewer.member(member?.handle),
+      })) || []
```
Comment (kdembler) [inline packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx]: What exactly are you trying to do here? If I understand the code correctly, this `.filter(({ channel }) => channel?.id !== id)` will have no effect. In line 105, we provide a filter to fetch only collectors for this specific channel so all the entries in that list will have that channel ID. What is the goal here?

**Review by kdembler — CHANGES_REQUESTED** [review]

File: packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx (hunk 1 above)
Comment (rafalpawlow) [reply packages/atlas/src/views/viewer/ChannelView/ChannelView.tsx]: Yeah, you are right, this is bullsh**t. I was trying to resolve the same problem we had in NftWidget and NftTile.
My channel has 1 NFT and CollectorsBox shows wrong owner. In that case, I'm not sure we'll be able to solve it.

Zrzut ekranu 2022-10-5 o 09 45 13

**Review by kdembler — APPROVED** [review]
