### PR TITLE
Fix broken text in NFT listing summary

### LINKED ISSUE #2889: Broken text in NFT listing summary
Screenshot 2022-06-21 at 12 32 38

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2889

### CODE REVIEW

File: packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ export const AcceptTerms: FC<AcceptTermsProps> = ({ selectedType, formData }) =>
               <Description>
                 <DescriptionText>{totalDaysAndHours}</DescriptionText>
                 <Text as="span" variant="h400" color="colorText">
-                  &nbsp;/ <NumberFormat as="span" value={durationBlocks} variant="h400" /> blocks
+                  &nbsp; / <NumberFormat value={durationBlocks} secondary variant="no-variant" /> blocks
```
Comment (drillprop) [inline packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/AcceptTerms/AcceptTerms.tsx]:
```suggestion
                  &nbsp; / <NumberFormat as="span" value={durationBlocks} secondary variant="no-variant" /> blocks
```

**Review by eldiegod — APPROVED** [review]
