### PR TITLE
Fix issue with updating video without thumbnail

### LINKED ISSUE #581: It's possible to update video with no thumbnail
if you remove the thumbnail, but not replace it, you can actually still publish changes. 
After the transaction is done, the thumbnail will remain the same though. 
upload bug

### PR DESCRIPTION
**Pull request by drillprop**
Should fix #581

### CODE REVIEW

**Review by mikkio-j — APPROVED** [review]

File: src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx [hunk 1]
```diff
@@ -221,7 +221,7 @@ export const EditVideoForm: React.FC<EditVideoFormProps> = ({
       setFileSelectError('Video file cannot be empty')
       return
     }
-    if ((!isEdit || dirtyFields.assets?.thumbnail) && !data.assets.thumbnail?.blob) {
+    if (!data.assets.thumbnail?.url && !dirtyFields.assets?.thumbnail) {
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx]: It seems to work but I don't understand how. The condition for the error is `no URL and field not dirty`. How does that work for a new video? In that case the field shouldn't be dirty if the thumbnail wasn't provided right?

Comment (drillprop) [reply src/views/studio/EditVideoSheet/EditVideoForm/EditVideoForm.tsx]: Oh, wait. I just noticed that `dirtyFields.assets?.thumbnail` is always `undefined`, no matter what you do with it. I could just set this to `if (!data.assets.thumbnail?.url)` and I'll do that

**Review by kdembler — APPROVED** [review]
