### PR TITLE
Fix NFT tile preview

### LINKED ISSUE #3027: NFT tile preview is empty when you click start sale from NFT tile's kebab menu
Happened to me only in the viewer: 
1. Go to membership/yourmembership
2. Click on the kebab menu and click put NFT on sale
3. Drawer should come up
4. Nft Tile doesn't contain any data: 
image

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #3027

### CODE REVIEW

File: packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx [hunk 1]
```diff
@@ -93,7 +93,7 @@ export const NftForm: FC<NftFormProps> = ({ setFormStatus, onSubmit, videoId })
     formState: { isValid },
   } = formMethods
 
-  const { video, loading: loadingVideo } = useFullVideo(videoId, { fetchPolicy: 'cache-only' })
+  const { video, loading: loadingVideo } = useFullVideo(videoId, { fetchPolicy: 'cache-first' })
```
Comment (drillprop) [inline packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx]: We could omit his option. `cache-first` is the default cache policy https://www.apollographql.com/docs/react/data/queries/#setting-a-fetch-policy

**Review by drillprop — CHANGES_REQUESTED** [review]

File: packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx (hunk 1 above)
Comment (kdembler) [reply packages/atlas/src/views/global/NftSaleBottomDrawer/NftForm/NftForm.tsx]: The question is - do we need a full video here? Maybe this component could work with just a basic video fragments? If yes, then we can even keep the current `fetchPolicy` as the basic video will already be in the cache

**Review by drillprop — APPROVED** [review]
LGTM!
