### PR TITLE
Featured NFTs carousel fixes

### LINKED ISSUE #4192: NFT on sale but not on auction not showing in featured carousels
## Context

https://dev.gleev.xyz/video/22

## Scope
- [ ] Include NFTs "Buy Now" that are not on auction but on sale to the featured carousel. 
- [ ] Exclude auction ended from Featured carousel
- [ ]  Update the order of the NFTs in the featured carousel:

1. NFTs on auction with timer, in asc order of time left (left to right), so the ones where sale ends soon show first
2. NFTs on open auction
3. NFTs on "buy now" 
4. NFTs with auction in the future
5. ~NFTs where auction is ended~

 + For 2 and 3 ordered by views desc
+ For 4 the sooner to start showing more on the left.

### PR DESCRIPTION
**Pull request by drillprop**
Fix #4192

### CODE REVIEW

File: packages/atlas/src/views/viewer/MarketplaceView/FeaturedNftsSection/FeaturedNftsSection.tsx [hunk 1]
```diff
@@ -50,30 +50,40 @@ const responsive: CarouselProps['breakpoints'] = {
...
-          isTypeOf_in: ['TransactionalStatusAuction', 'TransactionalStatusBuyNow'],
-          auction: {
-            isCompleted_eq: false,
+        OR: [
+          {
+            isFeatured_eq: true,
+            transactionalStatus: {
+              isTypeOf_eq: 'TransactionalStatusAuction',
+              auction: {
+                isCompleted_eq: false,
```
Comment (attemka) [inline packages/atlas/src/views/viewer/MarketplaceView/FeaturedNftsSection/FeaturedNftsSection.tsx:64]: auction could be also cancelled, should we also include it here?

**Review by attemka — APPROVED** [review]
