### PR TITLE
YPP\signup minor fixes

### LINKED ISSUE #4860: YPP OB fixes
1. Remove email pre-population entirely.
2. Tell user ` ⚠️ Please do not close the browser tab or reload the page` on the account created modal. As a separate paragraph. 
3. Remove suggestion to reach out to support chat when their channel is suspended. Update the link to notion to this [page>](https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b?pvs=4)

### PR DESCRIPTION
**Pull request by attemka**
#4860

### CODE REVIEW

File: packages/atlas/src/components/_auth/AuthenticationModalStepTemplate/AuthenticationModalStepTemplate.tsx [hunk 1]
```diff
@@ -57,9 +59,12 @@ export const AuthenticationModalStepTemplate: FC<AuthenticationModalStepTemplate
             </Text>
           </HeaderContainer>
           {subtitle && (
-            <Text variant="t200" as="span" color="colorText">
-              {subtitle}
-            </Text>
+            <>
+              {subtitleIcon}
+              <Text style={{ whiteSpace: 'pre-line' }} variant="t200" as="span" color="colorText">
```
Comment (WRadoslaw) [inline packages/atlas/src/components/_auth/AuthenticationModalStepTemplate/AuthenticationModalStepTemplate.tsx]: Inline style

**Review by WRadoslaw — APPROVED** [review]
Looks good besides that one nugget

File: packages/atlas/src/components/_auth/AuthenticationModalStepTemplate/AuthenticationModalStepTemplate.tsx (hunk 1 above)
Comment (attemka) [reply packages/atlas/src/components/_auth/AuthenticationModalStepTemplate/AuthenticationModalStepTemplate.tsx]: actually we don't even need it here since I changed subtitle to be from plain text to the reactNode. Thank you for noticing.
