### PR TITLE
Change NFT price fixes

### LINKED ISSUE #3109: Change NFT price fixes
- "Change price" option in ContextMenu doesn't work, clicking it doesn't trigger the dialog.

https://user-images.githubusercontent.com/12646744/184140189-60fcaacc-adbd-4979-b229-384bb6414463.mp4

- Let's add a fee to change price dialog
- Let's add "X" button in the top right corner so that users can quite to change price dialog

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #3109

### CODE REVIEW

File: packages/atlas/src/components/_overlays/ChangePriceDialog/ChangePriceDialog.tsx [hunk 1]
```diff
@@ -1,22 +1,36 @@
...
+  onChangePrice,
+  nftId,
+  memberId,
+}) => {
+  const [price, setPrice] = useState<number | null>(null)
+  const amountBn = tokenNumberToHapiBn(price || 0)
+  const { fullFee, loading: feeLoading } = useFee(
+    'changeNftPriceTx',
+    memberId && nftId ? [memberId, nftId, amountBn.toString()] : undefined
+  )
```
Comment (kdembler) [inline packages/atlas/src/components/_overlays/ChangePriceDialog/ChangePriceDialog.tsx]: Should we also add `isOpen` to the list of conditions for calculating this? Then fee isn't loaded until you actually want to change the price

**Review by kdembler — APPROVED** [review]
