### PR TITLE
Async failed outcomes

### LINKED ISSUE #1861: Async Failed Outcomes
**Context**
Transactions on NFT bidding that did not result in happy path outcome _after_  the bid was placed

**AC**

- [x] Refetch the NFT after a transaction error happens during NFT action
- [x] Find error codes for all of the errors below
- [x] Include some copy for each separate error

**List of errors**
- [x] English auction has expired
- [x] Somebody placed a higher bid in english auction already
- [x] Open auction winner has been picked before your bid has been processed
- [x] Somebody already bought NFT (buy now)
- [x] As an NFT owner, I want to pick open auction winner, but they have withdrawn their bid
- [x] Somebody has settled an auction already
- [x] Buy now price has changed after you wanted to buy it
- [x] As an NFT owner, I want to cancel my open auction but somebody has used buy now on it
- [x] As an NFT owner, I want to cancel my english auction but somebody has placed a bid

**Designs**

[General Figma Page >](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=985%3A96743)

### PR DESCRIPTION
**Pull request by drillprop**
fix #1861

### CODE REVIEW

File: packages/atlas/src/providers/transactionManager/useTransaction.ts [hunk 1]
```diff
@@ -99,19 +101,25 @@ export const useTransaction = (): HandleTransactionFn => {
         }
 
         if (errorName === 'FailedError') {
-          SentryLogger.error('Extrinsic failed', 'TransactionManager', error)
+          // extract error code from error message
+          const errorCode = Object.keys(ErrorCode).find((key) => error.message.includes(key))
+
+          SentryLogger.message(
```
Comment (kdembler) [inline packages/atlas/src/providers/transactionManager/useTransaction.ts]: This should still be `.error` call

**Review by kdembler — APPROVED** [review]
