### PR TITLE
Fix storybook build issue

### LINKED ISSUE #623: Storybook not working anymore
When you go to the storybook, you'll see just a loading screen, nothing more.

Possible solution - fix all the errors which are displayed in the console.

### PR DESCRIPTION
**Pull request by drillprop**
Should fix #623

### CODE REVIEW

**Review by kdembler — APPROVED** [review]

File: src/components/VideoGallery.tsx [hunk 1]
```diff
@@ -103,8 +104,8 @@ const StyledVideoPreview = styled(VideoPreview)`
   & + & {
     margin-left: ${sizes(6)};
   }
-
-  min-width: ${MIN_VIDEO_PREVIEW_WIDTH};
+  /* MIN_VIDEO_PREVIEW_WIDTH */
+  min-width: 300px;
```
Comment (kdembler) [inline src/components/VideoGallery.tsx:108]: 🙈
