### PR TITLE
Sign in flow minor fixes

### LINKED ISSUE #2067: Review - unified sign in flow
### Logic (@toiletgranny)

1. **[(0:00 – 1:39)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Polkadot account with JS membership not picked up instantly after being added in the extension**
   - **AS IS:** When I click on the "Sign in" button add then a Polkadot account with a JS membership associated with it in the extension, nothing happens in the app. I neec to close our internal Polkadot modal and click on the "Sign in" button again to have access to my membership.
   - **TO BE:** Ideally, our internal Polkadot modal is closed instantly, and the membership is available in the app the moment I add it to the Polkadot extension.
2. **[(1:40 – 2:10)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) The "Sign in" button not working when I remove/hide my Polkadot accounts in the extension**
   - **AS IS:** When I remove/hide _all_ my Polkadot accounts with a JS membership associated with them, the avatar in the Top navigation goes back to the "Sign in" button (cool!), but it doesn't do anything.
   - **TO BE:** The "Sign in" button brings up our internal Polkadot modal.
3. **[(2:10 – 2:52)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Membership dropdown remains open even after I remove/hide all of my Polkadot accounts**
   - **AS IS:** When I open up the Membership dropdown, having one or more Polkadot accounts with JS membership associated with them, and then remove/hide these accounts in the extension, the dropdown remains open but is empty.
   - **TO BE:**  Ideally, the membership dropdown either closes the moment I add/remove (hide/unhide) Polkadot accounts with JS membership associated with them in the extension, or it closes when there are no more active Polkadot accounts with JS memberships.
4. **[(2:52 – 3:23)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Membership dropdown preserving its state upon closing and reopening**
   - **AS IS:** When I open up the Membership dropdown and go into "Switch member" and close it, upon reopening I'm landing on that "Switch member" state.
   - **TO BE:**  Ideally, I always land on the initial, default state of the Membership dropdown each time I open it.
 5. **[(3:23 – 4:06)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Switching between viewer/studio is not consistent if I have memberships with channels and without them**
    - **AS IS:** When I go into Studio while browsing with a Membership without a channel, I'm landing on the channel creation page — fantastic. But then, if I switch my membership to a one with a channel, I land on my channel editing page, instead of on the initial Studio view, which is currently "My videos".
    - **TO BE:**  Ideally, in this case, the app redirects me to the "My videos" page.

### Visual differences (@Lenorette)

Divider should not appear there when there is no more content below. It should only appear when member has some channels.

When I hover over the avatar I can see hover state, it should not appear there.
Or if we want to leave it there when I click on the avatar, Membership edit page should open up with Avatar input active.

Distance between snackbar and bottom of the page is way to big, it should be 16px.

On hover, maybe it would be better to change copy to: "Copy Polkadot address"

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2067  
This should fix points 4 and 5 from logic, and every visual issue except the snack bar one.

### CODE REVIEW

File: packages/atlas/src/components/MembershipInfo/MembershipInfo.tsx [hunk 1]
```diff
@@ -86,7 +88,7 @@ export const MembershipInfo: React.FC<MembershipInfoProps> = ({
               ) : (
                 <StyledText variant="t300" secondary onClick={handleCopyAddress}>
                   {shortenAddress(address, 6, 4)}
-                  <Tooltip text="Copy address" arrowDisabled placement="top">
+                  <Tooltip text="Copy Polkadot address" arrowDisabled placement="top">
```
Comment (kdembler) [inline packages/atlas/src/components/MembershipInfo/MembershipInfo.tsx]:
```suggestion
                  <Tooltip text="Copy account address" arrowDisabled placement="top">
```

**Review by kdembler — APPROVED** [review]
