### PR TITLE
Fix infinite fetch loop on video delete

### LINKED ISSUE #627: Infinite fetch loop on video delete
I've found one case that makes the app break:

1. Have one video
2. Open the "Published" tab in my videos
3. Open the video edit
4. Click "Delete video" in the video sheet
5. The video will get deleted, and we will keep firing requests to refetch videos on the "Published" tab
6. If I go to "All videos" tab, the requests will stop and the app will hide the tabs and show the "No videos" state instead

My guess is that this will work the same without editing the video (with delete from the context menu). Anyway, we need to fix this

### PR DESCRIPTION
**Pull request by drillprop**
Fix #627

### CODE REVIEW

File: src/hooks/useDeleteVideo.tsx [hunk 1]
```diff
@@ -24,11 +16,7 @@ export const useDeleteVideo = () => {
 
     handleTransaction({
       txFactory: (updateStatus) => joystream.deleteVideo(videoId, activeMemberId, updateStatus),
-      onTxSync: async () => {
-        await refetchVideosCount()
-        removeVideoFromCache(videoId, client)
```
Comment (kdembler) [inline src/hooks/useDeleteVideo.tsx:29]: Why not keep that here?

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx [hunk 2]
```diff
@@ -203,18 +201,19 @@ export const EditVideoSheet: React.FC = () => {
...
           writeVideoDataInCache({
-            data: fetchedVideo.data.videoByUniqueInput,
+            edge: fetchedVideo.data.videosConnection.edges[0],
             thumbnailUrl: data.assets.thumbnail?.url,
             client,
           })
         }
         // update videos count only after inserting video in cache to not trigger refetch in "my videos" on missing video
-        await refetchVideosCount()
+        // !! await refetchVideosCount()
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: for removal

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx [hunk 3]
```diff
@@ -203,18 +201,19 @@ export const EditVideoSheet: React.FC = () => {
     }
 
     const refetchDataAndCacheAssets = async (videoId: VideoId) => {
-      const fetchedVideo = await refetchVideo({ where: { id: videoId } })
-
+      const fetchedVideo = await refetchVideoWithCursor({ where: { id_in: [videoId] } })
+      // const fetchVideoWithCursor = await
+      console.log(data.assets.thumbnail?.url)
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: for removal

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx [hunk 4]
```diff
@@ -203,18 +201,19 @@ export const EditVideoSheet: React.FC = () => {
     }
 
     const refetchDataAndCacheAssets = async (videoId: VideoId) => {
-      const fetchedVideo = await refetchVideo({ where: { id: videoId } })
-
+      const fetchedVideo = await refetchVideoWithCursor({ where: { id_in: [videoId] } })
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: I think better pattern for when we need to fetch something conditionally and only once is to do something like we currently have in  `CreateMemberView`:
```ts
await client.query<GetMembershipQuery, GetMembershipQueryVariables>({
  query: GetMembershipDocument,
  variables: { where: { handle: value } },
})
```

File: src/utils/cachingAssets.ts [hunk 5]
```diff
@@ -65,21 +68,28 @@ export const writeUrlInCache = ({ url, fileType, parentId, client }: WriteUrlInC
...
+          ...existingVideos,
+          pageInfo: {
+            ...existingVideos.pageInfo,
+          },
+          totalCount: existingVideos.totalCount + 1,
+          edges: [{ ...edge, node: video }, ...(existingVideos?.edges ? existingVideos.edges : [])],
+        }
       },
     },
   })
```
Comment (kdembler) [inline src/utils/cachingAssets.ts:92]: Below here, we also need to make change to `removeVideoFromCache` to modify `videosConnection` query as well

File: src/utils/cachingAssets.ts [hunk 6]
```diff
@@ -65,33 +68,51 @@ export const writeUrlInCache = ({ url, fileType, parentId, client }: WriteUrlInC
...
+
+export const removeVideoFromCache = (videoId: string, client: ApolloClient<object>) => {
   client.cache.modify({
     fields: {
       videos: (existingVideos = []) => {
         client.cache.evict({ id: `Video:${videoId}` })
         return existingVideos.filter((video: VideoFieldsFragment) => video.id !== videoId)
       },
+      videosConnection: (existing = {}, opts) => {
+        client.cache.evict({ id: `Video:${videoId}` })
```
Comment (kdembler) [inline src/utils/cachingAssets.ts]: Let's move evict out of `cache.modify`

File: src/utils/cachingAssets.ts [hunk 7]
```diff
@@ -65,33 +68,51 @@ export const writeUrlInCache = ({ url, fileType, parentId, client }: WriteUrlInC
...
+        return (
+          existing && {
+            ...existing,
+            totalCount: existing.totalCount - 1,
```
Comment (kdembler) [inline src/utils/cachingAssets.ts]: This will result in decrementing `totalCount` regardless of whether the given video was actually included in that query cache, right? E.g. I delete public video but `totalCount` is decremented for queries targeting only unlisted videos as well. Correct?

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx [hunk 8]
```diff
@@ -203,18 +198,24 @@ export const EditVideoSheet: React.FC = () => {
...
+      const fetchedVideo = await client.query<GetVideosConnectionQuery, GetVideosConnectionQueryVariables>({
+        query: GetVideosConnectionDocument,
+        variables: {
+          where: {
+            channelId_eq: activeChannelId,
+            isPublic_eq: data.isPublic,
+            id_eq: videoId,
+          },
+        },
+      })
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: Why do we use a connection here instead of a regular `videoByUniqueInput` query? We care only about one video details, right?

Comment (drillprop) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: I think it works and I'll change that, but what about the `cursor` field? I cannot add a video cursor to the cache when I do the `videoByUniqueInput` query. Do we need that in this case?

File: src/utils/cachingAssets.ts (hunk 7 above)
Comment (drillprop) [reply src/utils/cachingAssets.ts]: Yes, you're right - should be fixed now.

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx (hunk 8 above)
Comment (drillprop) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: Noticed one more thing - when I'm using `videoByUniqueInput` after adding video it refetches the whole `videosConnection` list. When I'm using `videosConnection` it doesn't. To be honest, I'm not sure why. 

Also,  I need to do something with `totalCount: existing.totalCount + 1`, because analogous to `removeVideoFromCache`, `totalCount` is incremented in unlisted, public and all videos query.

Comment (kdembler) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: > Noticed one more thing - when I'm using videoByUniqueInput after adding video it refetches the whole videosConnection list.

Hmm that's weird.

Maybe let's use `videosConnection` after all, it will give us a cursor as well. However, if we want to get the same cursor as other queries, we will need to add `orderBy` here, it changes the cursor.

Comment (kdembler) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: Regarding totalCount I'm not sure... it's messy. I think once we get a normalized cache, we can just return `totalCount` locally instead

Comment (kdembler) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: Does it break things a lot right now or can we ignore it for the time being?

Comment (drillprop) [reply src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: >Maybe let's use videosConnection after all, it will give us a cursor as well. However, if we want to get the same cursor as other queries, we will need to add orderBy here, it changes the cursor.

So, I'll revert that.

> Does it break things a lot right now or can we ignore it for the time being?

Not really. I think we can ignore it for now.

File: src/views/studio/EditVideoSheet/EditVideoSheet.tsx [hunk 9]
```diff
@@ -203,18 +198,24 @@ export const EditVideoSheet: React.FC = () => {
...
-
+      const fetchedVideo = await client.query<GetVideosConnectionQuery, GetVideosConnectionQueryVariables>({
+        query: GetVideosConnectionDocument,
+        variables: {
+          where: {
+            channelId_eq: activeChannelId,
+            isPublic_eq: data.isPublic,
+            id_eq: videoId,
+          },
+        },
```
Comment (kdembler) [inline src/views/studio/EditVideoSheet/EditVideoSheet.tsx]: We will need `orderBy` here to make sure we get the same cursor. Also, do we need `channelId_eq` and `isPublic_eq` here?

**Review by kdembler — APPROVED** [review]
