### PR TITLE
Fix issue with flashing welcome studio view

### LINKED ISSUE #2014: Fix issue with showing StudioWelcomeView for a split second when the user is signed
This happens on `signin` branch

### PR DESCRIPTION
**Pull request by drillprop**
Fix #2014

### CODE REVIEW

File: packages/atlas/src/views/studio/StudioLayout.tsx [hunk 1]
```diff
@@ -61,62 +68,74 @@ const StudioLayout = () => {
...
+                  <PrivateRoute element={<MyUploadsView />} isAuth={channelSet} redirectTo={ENTRY_POINT_ROUTE} />
+                }
+              />
+              <Route
+                path={relativeRoutes.studio.videos()}
+                element={<PrivateRoute element={<MyVideosView />} isAuth={channelSet} redirectTo={ENTRY_POINT_ROUTE} />}
+              />
+            </Routes>
+          </MainContainer>
+          {channelSet && <VideoWorkspace />}{' '}
```
Comment (kdembler) [inline packages/atlas/src/views/studio/StudioLayout.tsx]: Space at the end not needed I think?

**Review by kdembler — COMMENTED** [review]
Seems to work fine for solving the issue, but wen need to fix the issue with member update extrinsic

File: packages/atlas/src/views/studio/StudioLayout.tsx (hunk 1 above)
Comment (kdembler) [inline packages/atlas/src/views/studio/StudioLayout.tsx]:
```suggestion
          {channelSet && <VideoWorkspace />}
```

**Review by kdembler — APPROVED** [review]

**Review by kdembler — APPROVED** [review]
