### PR TITLE
🍸 YPP cosmetics

### LINKED ISSUE #3527: YPP cosmetic fixes
## Context

@toiletgranny has been reviewing the designs and found a few cosmetic small and medium bugs.  This ticket encapsulates the fixes described in the spreadsheet: 
- https://docs.google.com/spreadsheets/d/1B-AgxGIRTfFGD0-XoVK_vUFp2d6n9TpL1VUEbEgDj6M/edit#gid=0

Rows: 2,3,4,5,7, 8

## Scope
 Fix cosmetic bugs covered in the spreadsheet:
 
1️⃣ 
As is:
YPP page <title> says "Youtube Partner Program"

To-be: 
The YouTube name should always be displayed with a capital "You" and capital "Tube".

2️⃣ 
As is:
In the Requirements step of the Authorize channel dalog, the list of requirements fills the width of the parent container.

To-be:
There should be 64px of right padding applied on the list of requirements to make the text easier to read.

3️⃣ 
As is:
In the Requirements step of the Authorize channel dalog, in the "Your YouTube channel has at least 1 subscribers" requirement, the word "subscribers" is plural and hard-coded 

To-be:
The word "subscribers" should be in a singular form if the required number of subscribers is set to 1.

4️⃣ 
As-is:
In the "Connect with YouTube?" dialog
1. The YouTube name is displayed as "youtube",
2. The "Learn more" button doesn't work,
3. The "Close" button is labeled as "Cancel" and redirects the user to 

To-be:
1. The YouTube name should always be displayed with a capital "You" and capital "Tube". Basically, the copy shoudl be copied from Figma.
2. The "Learn more" button should open up the YPP page on Publisher,
3. The "Cancel" button should be labelled as "Close", as per Figma designs.

5️⃣ 

As-is:
In the Details step of the Authorize channel dalog:
1. The form description says "We need your email address to send you payment information. No spam or marketing materials.",
2. The form contains error messages that do not reflect the copy provided in Figma,
3. The Select component is not in its Error styling variant when not filled out (it doesn't have a red underline).

To-be:
1. The form description should match the copy provided in Figma, so it should begin with "Provide additional information...",
2. All copy should match the one provided in Figma,
3. The Select component should be in its Error styling variant.

6️⃣ 
As-is: 
referrer field has channel input and placeholder copy says "Channel handle" 

T0-be: 
Update to "Channel Name"

### PR DESCRIPTION
**Pull request by WRadoslaw**
fixes #3527

### CODE REVIEW

File: packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationSteps/YppAuthorizationDetailsFormStep/YppAuthorizationDetailsFormStep.tsx [hunk 1]
```diff
@@ -159,7 +165,7 @@ export const YppAuthorizationDetailsFormStep: FC = () => {
             )
           }
           {...titleRegisterRest}
-          placeholder="Channel handle"
+          placeholder="Channel Name"
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationSteps/YppAuthorizationDetailsFormStep/YppAuthorizationDetailsFormStep.tsx]: I cannot comment on this line, but on line 156  we have `Enter the title of the Joystream channel which recommended the program to you.` This doesn't seem right to me as well. It would make sense to have `Joystream member` here, but not a channel. It should be `Enter the title of the ${atlasConfig.general.appName} channel which recommended the program to you.`

Could you also update this?

File: packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx [hunk 2]
```diff
@@ -306,7 +308,7 @@ export const YppAuthorizationModal: FC<YppAuthorizationModalProps> = ({
       {
         text: `Your YouTube channel has at least ${formatNumber(
           fetchedChannelRequirements?.MINIMUM_SUBSCRIBERS_COUNT || 0
-        )} subscribers`,
+        )} subscriber${fetchedChannelRequirements?.MINIMUM_SUBSCRIBERS_COUNT !== 1 ? 's' : ''}`,
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx]: We have a helper function for this `pluralizeNoun`. We could use this here. Not a biggie though

File: packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx [hunk 3]
```diff
@@ -296,7 +296,9 @@ export const YppAuthorizationModal: FC<YppAuthorizationModalProps> = ({
       {
         text: `Your YouTube channel has at least ${formatNumber(
           fetchedChannelRequirements?.MINIMUM_VIDEO_COUNT || 0
-        )} videos, all published at least ${convertHoursRequirementTime(
+        )} video${
+          fetchedChannelRequirements?.MINIMUM_VIDEO_COUNT !== 1 ? 's' : ''
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.tsx]: same here

**Review by drillprop — APPROVED** [review]
