### PR TITLE
Giza: tweaks and fixes

### LINKED ISSUE #1718: Atlas Giza testing and tweaking
Scope:

- [ ] Remove any TODO items from initial Giza PRs
- [ ] Fix re-uploading
- [ ] Fix failed video tile when updating the video thumbnail
- [ ] Estimate fee of uploading
- [ ] Use WASM for blake3 hashing
- [ ] Update dimensions of uploaded images
- [ ] Handle refetching bucket assignements when creating a new channel

### PR DESCRIPTION
**Pull request by kdembler**
Fixes #1718 

- [x] Remove any TODO items from initial Giza PRs
- [x] Fix re-uploading
- [x] Fix failed video tile when updating the video thumbnail
- [x] ~Estimate fee of uploading~
- [x] Use WASM for blake3 hashing
- [x] Update dimensions of uploaded images
- [x] Handle refetching bucket assignements when creating a new channel
- [x] Handle no user avatar

### CODE REVIEW

File: src/providers/transactionManager/transactionManager.tsx [hunk 1]
```diff
@@ -20,6 +20,10 @@ export const TransactionManager: React.FC = () => {
       if (!subscriptionData.data) return
 
       const indexerHead = subscriptionData.data.stateSubscription.indexerHead
+
+      // TODO: remove
+      // eslint-disable-next-line no-console
+      console.log('got QN block: ', indexerHead)
```
Comment (kdembler) [inline src/providers/transactionManager/transactionManager.tsx]: This is left here purposefully for now, will remove later

**Review by drillprop — APPROVED** [review]

**Review by eldiegod — APPROVED** [review]

**Review by rafalpawlow — APPROVED** [review]
