### PR TITLE
Fix layout shift on popular page

### LINKED ISSUE #1187: Layout change when loading Popular page
https://user-images.githubusercontent.com/12646744/129579850-f2b7de59-9be6-4dc3-aac4-2e79273c3d73.mov

As you can see, when you load the Popular page there's a change of content. There's a `Popular videos` section visible for a split second only to be pushed down by `Top 10 this month`. I think we should show a placeholder for the first section right away to avoid this jump

### PR DESCRIPTION
**Pull request by drillprop**
Fix #1187
Also: 
- fix the skeleton loader in InfiniteVideoGrid
- fix the follow button on ChannelWithVideos(the app was navigating to channel when user clicks follow/unfollow)

### CODE REVIEW

File: src/components/InfiniteGrids/InfiniteVideoGrid.tsx [hunk 1]
```diff
@@ -173,7 +173,11 @@ export const InfiniteVideoGrid: React.FC<InfiniteVideoGridProps> = ({
       <TitleWrapper>
         {title && (
           <GridHeadingContainer>
-            {!ready ? <SkeletonLoader height={23} width={250} /> : <Text variant="h4">{title}</Text>}
+            {loading || !displayedItems.length ? (
```
Comment (kdembler) [inline src/components/InfiniteGrids/InfiniteVideoGrid.tsx]: We're ignoring the `ready` props now. Was that the plan?

**Review by kdembler — CHANGES_REQUESTED** [review]
Unfortunately there are still some issues with jumping. Take a look at this (New view):

https://user-images.githubusercontent.com/12646744/129763714-93e54b93-e5c5-4c61-81fc-4d41caa02080.mov

You can see 2 jumps here:
1. The placeholder jumps down and back up a bit (not a biggie, we can skip if hard to fix)
2. The border under the title jumps down significantly after the skeleton disappears, we need to improve that

**Comment by drillprop** [comment]
Fixed, It should be good now

**Review by kdembler — APPROVED** [review]
