### PR TITLE
Minor improvements and fix video content pages typos

### LINKED ISSUE #1168: Video content pages typos and minor improvements
according to https://github.com/Joystream/atlas/issues/1131#issuecomment-898362969

 * [x]  "Official Joystream updates" shouldn't have "See all" button
 * [x]  We're lacking "Discover new channels" section in `Home`
 * [x]  `Top 10 Channels` header should be `Top 10 channels`
 * [x]  `Discover channels` header should be `Discover new channels`
* [x]  "Official Joystream updates" and "Top 10 this week" in `Home` are in wrong order
 * [x]  We should remove the old `Videos` view

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #1168

### CODE REVIEW

File: src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx [hunk 1]
```diff
@@ -26,16 +26,6 @@ const viewerSidenavItems: NavItemType[] = [
     name: 'New',
     to: absoluteRoutes.viewer.new(),
   },
-  {
-    icon: <SvgNavVideos />,
-    name: 'Videos',
-    to: absoluteRoutes.viewer.videos(),
-  },
-  {
-    icon: <SvgNavChannels />,
```
Comment (kdembler) [inline src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx:35]: Should have mentioned earlier but let's keep that link inside the navigation for now even though it's missing in the designs

Comment (drillprop) [reply src/components/Sidenav/ViewerSidenav/ViewerSidenav.tsx:35]: fixed

**Review by kdembler — APPROVED** [review]
