### PR TITLE
Fix video player error overlay

### LINKED ISSUE #1640: Video player error overlay allows starting playback
**Describe the bug**

If there's some issue and the error overlay appears in the video player, it's possible to click the background of it and force to player to start playback.

**To Reproduce**

1. Go to https://play.joystream.org/video/7815
2. Click the greyed out background
3. Player loading is triggered

**Expected behavior**

It shouldn't be possible to tigger the playing state, error should be persistent

**Screenshots**

https://user-images.githubusercontent.com/12646744/143215640-303650cf-dd8e-43e5-96a0-da0fc74be93f.mov

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #1640

### CODE REVIEW

**Comment by kdembler** [comment]
I think @drillprop may be a better fit for reviewer here

File: src/components/_video/VideoPlayer/VideoPlayer.tsx [hunk 1]
```diff
@@ -416,13 +416,16 @@ const VideoPlayerComponent: React.ForwardRefRenderFunction<HTMLVideoElement, Vid
   }, [currentVolume, volumeToSave, player, setCachedVolume])
 
   // button/input handlers
-  const handlePlayPause = () => {
+  const handlePlayPause = useCallback(() => {
+    if (playerState === 'error') {
```
Comment (drillprop) [inline src/components/_video/VideoPlayer/VideoPlayer.tsx:420]:
```suggestion
    if (playerState === 'error' || playerState === 'ended') {
```
This is happens also when a video is ended. I think it makes sense to refactor this line

**Review by drillprop — CHANGES_REQUESTED** [review]
Also, I found that the text on the ending screen is not centered. Could we also fix this in one go? Should be relatively easy.
image
 
I think this is because the paragraph beneath the title is a `span` now and should be `paragraph`. You could just add `as="p"` on the Text component if I'm not mistaken.

File: src/components/_video/VideoPlayer/VideoPlayer.tsx (hunk 1 above)
Comment (drillprop) [reply src/components/_video/VideoPlayer/VideoPlayer.tsx:420]: Rafał just point me out that applying this suggestion will break the replay button on controls.

Anyway, I got confirmation from Adam that we shouldn't be able to replay a video by clicking on the background when a video is ended. We need to fix this at some point as well. 
I'll create a new issue just for this particular bug because it will require more changes to the code.

**Review by drillprop — APPROVED** [review]
Looks good to me 👍🏻
