### PR TITLE
Fix other filters logic

### LINKED ISSUE #1556: Other filters in search results page don't act like described
Those filters should exclude the given types of content, not filter by them

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #1556

### CODE REVIEW

File: src/api/client/cache.ts [hunk 1]
```diff
@@ -49,13 +49,15 @@ const getChannelKeyArgs = (args: Record<string, GetChannelsConnectionQueryVariab
 const getSearchKeyArgs = (args: Record<string, SearchQueryVariables['whereVideo']> | null) => {
   const text = args?.text || ''
   const licenseIdIn = args?.whereVideo?.licenseId_in || []
-  const hasMarketingEq = args?.whereVideo?.hasMarketing_eq || ''
-  const isExplicitEq = args?.whereVideo?.isExplicit_eq || ''
+  const hasMarketingEq = args?.whereVideo?.hasMarketing_eq || true
+  const isExplicitEq = args?.whereVideo?.isExplicit_eq || true
```
Comment (kdembler) [inline src/api/client/cache.ts]: Why are we assuming `true` for those if they're missing? This can lead to wrong results

File: src/hooks/useSearchResults.ts [hunk 2]
```diff
@@ -42,6 +42,7 @@ export const useSearchResults = ({ searchQuery, limit = 50, videoWhereInput }: S
       },
     },
     {
+      fetchPolicy: 'no-cache',
```
Comment (kdembler) [inline src/hooks/useSearchResults.ts]: Why `no-cache`? This will force us to make network request on every filter change even if we already know the result, right?

**Review by kdembler — APPROVED** [review]
