### PR TITLE
🩹 Additional ypp status when no wallet connected

### LINKED ISSUE #3498: YPP incorrect button copy on LP when not signed in
Seems we're not following the design when the user is not signed in at all:

Design: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1789%3A131584&t=90bmnb9deHVVTpQP-4

CleanShot 2022-12-07 at 13 08 11@2x

### PR DESCRIPTION
**Pull request by WRadoslaw**
fixes #3498

### CODE REVIEW

File: packages/atlas/src/views/global/YppLandingView/YppHero.tsx [hunk 1]
```diff
@@ -47,6 +47,8 @@ const getButtonText = (variant: YppStatus) => {
       return 'Sign up now'
     case 'no-channel':
       return 'Create channel & sign up'
+    case 'connect-wallet':
+      return 'Connect wallet'
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppHero.tsx]: I checked the design and I think this is supposed to be `Sign up now` as well? 

Check here:  https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1774%3A115618&t=X01XdRaPbcksmb7b-4

File: packages/atlas/src/views/global/YppLandingView/YppHero.tsx [hunk 2]
```diff
@@ -113,8 +115,8 @@ export const YppHero: FC<YppHeroProps> = ({
                     <Button
                       size="large"
                       variant={yppStatus === 'ypp-signed' ? 'secondary' : 'primary'}
-                      icon={<SvgActionChevronR />}
-                      iconPlacement="right"
+                      icon={yppStatus === 'connect-wallet' ? <SvgActionMember /> : <SvgActionChevronR />}
+                      iconPlacement={yppStatus === 'connect-wallet' ? 'left' : 'right'}
```
Comment (drillprop) [inline packages/atlas/src/views/global/YppLandingView/YppHero.tsx]: Again, according to the design, there is no icon change in this case

**Review by drillprop — CHANGES_REQUESTED** [review]

**Review by drillprop — APPROVED** [review]
