### PR TITLE
fix clipped popovers

### LINKED ISSUE #2610: Fix clipped popovers in section headers
When opening the filters popover in the Channel page, the NFTs tab, the component is clipped if displayed above the trigger element.

https://user-images.githubusercontent.com/35307309/166924214-d2fa225e-3f0c-4f72-8991-7cea15ecb2fb.mp4

### PR DESCRIPTION
**Pull request by rafalpawlow**
Closes #2610

### CODE REVIEW

File: packages/atlas/src/components/_overlays/Popover/Popover.tsx [hunk 1]
```diff
@@ -90,6 +92,9 @@ const _Popover: React.ForwardRefRenderFunction<PopoverImperativeHandle | undefin
           {children}
         </ContentContainer>
       )}
+      popperOptions={{
+        modifiers: [{ name: 'flip', enabled: flipEnabled }],
```
Comment (drillprop) [inline packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: I'm wondering, do we actually want this flip behavior enabled in the entire app? I think we should disable this and not worry about passing the `flipEnabled` prop.

**Review by drillprop — CHANGES_REQUESTED** [review]

File: packages/atlas/src/components/_overlays/Popover/Popover.tsx (hunk 1 above)
Comment (rafalpawlow) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: I'm not sure if this is a good idea, this might be helpful for tooltips

Comment (kdembler) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: What exactly are we discussing here?

Comment (drillprop) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: If you look at Adam's video you'll notice that the popover changes his position when there is not much space for this context menu in the viewport. And I'm guessing this is the default behavior in Popover

https://user-images.githubusercontent.com/35307309/166924214-d2fa225e-3f0c-4f72-8991-7cea15ecb2fb.mp4

My proposition was to just turn off this behavior, and don't add a prop that could control this as Rafał did.

Comment (kdembler) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: Oh, I would say that we should keep this on always. :P It's a good UX, for some popovers there won't be enough space to display them below. The solution isn't to not flip them, but to make sure they remain visible when flipped

Comment (rafalpawlow) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: @kdembler I'm affraid this won't be possible in the case above because of z-indexes.

Comment (kdembler) [reply packages/atlas/src/components/_overlays/Popover/Popover.tsx:96]: What do you mean? Can't we change those z-indexes?

File: packages/atlas/src/components/_overlays/Popover/Popover.tsx [hunk 2]
```diff
@@ -90,6 +90,7 @@ const _Popover: React.ForwardRefRenderFunction<PopoverImperativeHandle | undefin
           {children}
         </ContentContainer>
       )}
+      appendTo={document.body}
```
Comment (rafalpawlow) [inline packages/atlas/src/components/_overlays/Popover/Popover.tsx]: https://github.com/atomiks/tippyjs-react/issues/207

**Review by drillprop — APPROVED** [review]
Looks good to me. @kdembler could you look as well, since you had some concerns about the previous approach? 

Edit: Oh, this will be merged into `dev` so you need to approve anyway 😅

**Review by kdembler — APPROVED** [review]
