### PR TITLE
Fix deleting cover image when creating channel

### LINKED ISSUE #3237: Can't delete channel cover when creating a channel
**Sender**: pavellusikov@gmail.com
**Taken at**: https://play.joystream.org/studio/channel/new
**Fields**:
- Expected Result: Now you can&#39;t change the cover image when creating a channel. If I accidentally uploaded the wrong picture and want to change it, then don&#39;t do it now.
There is no such problem with uploading an avatar. If I uploaded the wrong one, I can click &#34;Delete&#34; and it will be deleted.
- Houston, we have a problem.: Bug with cover image in creating a channel

SCREENSHOT
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/56429f71-a2d2-4f91-8278-2e23605bb2cd-annotated_ada58a21-8efb-44d1-a533-5e791e1e88cc.png?etag=51a0aee3bd5ecdc77f68979fdfaad6e0)*

**Browser**: Chrome 104 (Windows 8.1)
**Screen size**: 1366x768
**Browser size**: 1366x695
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/db445413-7bec-4de1-bf19-b2c54ca94db8_screen_recording_d2b277fb-190b-45ae-88d6-a58791c5d506.webm?etag=d3e490caa791090480d0d0d3e3027e15)**
**[Open #21 in Usersnap](https://app.usersnap.com/l/feedback/67ca9ff1-d3be-4b57-9c44-cd93034e893a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

### PR DESCRIPTION
**Pull request by rafalpawlow**
Fixes #3237

### CODE REVIEW

File: packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx [hunk 1]
```diff
@@ -555,6 +563,7 @@ export const CreateEditChannelView: FC<CreateEditChannelViewProps> = ({ newChann
             <ImageCropModal
               imageType="cover"
               onConfirm={handleCoverChange}
+              onDelete={handleDeleteCover}
```
Comment (kdembler) [inline packages/atlas/src/views/studio/CreateEditChannelView/CreateEditChannelView.tsx:566]: Maybe we either:
a) make this prop required
b) hide the `Delete` button if this callback is not defined

This way we avoid situations like this in the future

**Review by drillprop — APPROVED** [review]
