### PR TITLE
Failed upload tile

### LINKED ISSUE #1440: Update Video Tile variant for failed video uploads
We should have a Video Tile variant for when the upload of video file failed, like we do for currently uploading. This isn't an actionable item for the dev team but rather here to not forget this point

### PR DESCRIPTION
**Pull request by drillprop**
Fix #1440 
Design: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=1903%3A94487

### CODE REVIEW

File: src/components/VideoTilePublisher.tsx [hunk 1]
```diff
@@ -40,11 +41,12 @@ export const VideoTilePublisher: React.FC<VideoTileWPublisherProps> = ({ id, isD
       duration={video?.duration}
       views={video?.views}
       thumbnailUrl={thumbnailPhotoUrl}
-      hasThumbnailUploadFailed={hasThumbnailUploadFailed}
+      hasAssetUploadFailed={hasAssetUploadFailed}
       channelHref={id ? absoluteRoutes.viewer.channel(video?.channel.id) : undefined}
       isLoading={loading}
       onOpenInTabClick={isDraft || !id ? undefined : () => openInNewTab(absoluteRoutes.viewer.video(id), true)}
       onCopyVideoURLClick={isDraft ? undefined : () => copyToClipboard(videoHref ? location.origin + videoHref : '')}
+      onReuploadVideoClick={isDraft ? undefined : () => copyToClipboard(videoHref ? location.origin + videoHref : '')}
```
Comment (kdembler) [inline src/components/VideoTilePublisher.tsx]: What's going on here?

File: src/shared/components/VideoTileBase/VideoTileCover.tsx [hunk 2]
```diff
@@ -0,0 +1,220 @@
...
+  CoverVideoPublishingStateOverlay,
+  CoverWrapper,
+  DELAYED_FADE_CLASSNAME,
+  PublishingStateText,
+  RemoveButton,
+  SkeletonHoverOverlay,
+  UploadProgressTransition,
+} from './VideoTileCover.style'
+
+import { VideoTileBaseMetaProps, VideoTilePublisherProps } from '.'
```
Comment (kdembler) [inline src/shared/components/VideoTileBase/VideoTileCover.tsx]: This will be a circular dependency right? Does `VideoTileCoverProps` need all the other props?

File: src/shared/components/VideoTileBase/VideoTileCover.tsx [hunk 3]
```diff
@@ -0,0 +1,220 @@
...
+  publisherMode,
+  videoPublishState,
+  duration,
+  isPullupDisabled,
+  onPullupClick,
+  removeButton,
+  title,
+  channelTitle,
+}) => {
+  const [failedLoadImage, setFailedLoadImage] = useState(false)
```
Comment (kdembler) [inline src/shared/components/VideoTileBase/VideoTileCover.tsx]: I wonder whether we still need that? `useAsset` should catch all the errors with images so I guess with the new functionality you've added we could remove that?

**Comment by kdembler** [comment]
Also, this is displayed when the upload is still ongoing:
Screenshot 2021-10-11 at 08 26 43

File: src/shared/components/VideoTileBase/VideoTileCover.tsx (hunk 3 above)
Comment (drillprop) [reply src/shared/components/VideoTileBase/VideoTileCover.tsx]: yeah, we don't need this anymore

**Review by kdembler — APPROVED** [review]
